[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "jdatetime>=5.2.0",
    "pytz>=2025.1",
    "qrcode>=8.0",
    "requests>=2.32.3",
    "telethon>=1.39.0",
]
